version: "3.7"
services:
  app:
    build:
      args:
        user: nick
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: img1
    container_name: cont1
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - net1
  db:
    image: mysql:8.0
    container_name: db-container-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - net1
  nginx:
    image: nginx:alpine
    container_name: nginx1
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - net1
networks:
  net1:
    driver: bridge